insert into base_address (street, city, customer_id, country) values ('Red Cloud', 'Manzini', '30', 'Swaziland');
insert into base_address (street, city, customer_id, country) values ('Crownhardt', 'Xinglongjie', '39', 'China');
insert into base_address (street, city, customer_id, country) values ('Badeau', 'Toritama', '33', 'Brazil');
insert into base_address (street, city, customer_id, country) values ('Sunbrook', 'Limonade', '4', 'Haiti');
insert into base_address (street, city, customer_id, country) values ('Orin', 'Xiwei', '5', 'China');
insert into base_address (street, city, customer_id, country) values ('Esker', 'Tetyushi', '6', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Scoville', 'Harper', '7', 'Liberia');
insert into base_address (street, city, customer_id, country) values ('Riverside', 'Hōfu', '8', 'Japan');
insert into base_address (street, city, customer_id, country) values ('Mcguire', 'Miaoli', '9', 'Taiwan');
insert into base_address (street, city, customer_id, country) values ('Center', 'Mogzon', '10', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Debs', 'Inabaan Sur', '11', 'Philippines');
insert into base_address (street, city, customer_id, country) values ('Bartillon', 'Río Viejo', '12', 'Colombia');
insert into base_address (street, city, customer_id, country) values ('Manley', 'Puqian', '13', 'China');
insert into base_address (street, city, customer_id, country) values ('Steensland', 'Jiangfang', '14', 'China');
insert into base_address (street, city, customer_id, country) values ('Hanson', 'Burmakino', '25', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Dorton', 'Delgermörön', '16', 'Mongolia');
insert into base_address (street, city, customer_id, country) values ('Moland', 'Umeå', '17', 'Sweden');
insert into base_address (street, city, customer_id, country) values ('Comanche', 'Boynton Beach', '18', 'United States');
insert into base_address (street, city, customer_id, country) values ('Nova', 'Puyang', '19', 'China');
insert into base_address (street, city, customer_id, country) values ('Park Meadow', 'Haeju', '20', 'North Korea');
insert into base_address (street, city, customer_id, country) values ('Hoffman', 'Vikhorevka', '23', null);
insert into base_address (street, city, customer_id, country) values ('Mcguire', 'Mardzad', '22', 'Mongolia');
insert into base_address (street, city, customer_id, country) values ('North', 'Lyuban’', '21', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Dakota', 'Eskifjörður', '40', 'Iceland');
insert into base_address (street, city, customer_id, country) values ('Monterey', 'Uga', '15', 'Nigeria');
insert into base_address (street, city, customer_id, country) values ('Warbler', 'Wonokerto', '26', 'Indonesia');
insert into base_address (street, city, customer_id, country) values ('Corry', 'Guandu', '27', 'China');
insert into base_address (street, city, customer_id, country) values ('Haas', 'Ḥurfeish', '38', 'Israel');
insert into base_address (street, city, customer_id, country) values ('Fairfield', 'Huaitu', '29', 'China');
insert into base_address (street, city, customer_id, country) values ('Oneill', 'Al Jawādīyah', '1', 'Syria');
insert into base_address (street, city, customer_id, country) values ('Bultman', 'Zhili', '31', 'China');
insert into base_address (street, city, customer_id, country) values ('Arkansas', 'Shipu', '32', 'China');
insert into base_address (street, city, customer_id, country) values ('Eliot', 'Cachoeira', '3', 'Brazil');
insert into base_address (street, city, customer_id, country) values ('Bashford', 'Tamiso', '34', 'Philippines');
insert into base_address (street, city, customer_id, country) values ('Brickson Park', 'Rancapare', '35', 'Indonesia');
insert into base_address (street, city, customer_id, country) values ('Ilene', 'Tianjiazhuang', '36', 'China');
insert into base_address (street, city, customer_id, country) values ('Iowa', 'Khelyulya', '37', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Russell', 'Bol’shoye Skuratovo', '28', 'Russia');
insert into base_address (street, city, customer_id, country) values ('Jenna', '‘Irbīn', '2', 'Syria');
insert into base_address (street, city, customer_id, country) values ('Bunker Hill', 'Visby', '24', 'Sweden');
