# Generated by Django 4.2.5 on 2023-09-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_like_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
