# Generated by Django 4.2.5 on 2023-09-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='feature_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product'),
        ),
    ]
