# Generated by Django 4.2.5 on 2023-09-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
