# Generated by Django 4.2.5 on 2023-09-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_catagory_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unite_price',
        ),
    ]
